# Site settings
title: НПК Спецоборудование
email: your-email@domain.com
url: https://example.github.io
description: "Напишите потрясающее описание для вашего нового сайта здесь. Вы можете редактировать эту строку в _config.yml. Он появится в мета заголовка документа (для результатов поиска Google) и в описании вашего сайта feed.xml."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: ООО НПК Спецоборудование

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
